# Generated by Django 3.2.15 on 2022-09-17 04:49

from django.db import migrations, models
import stoic_diary_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('stoic_diary_api', '0003_auto_20220917_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expiry_date',
            field=models.DateField(default=stoic_diary_api.models.get_expiry_date),
        ),
    ]
